-- CreateTable
CREATE TABLE "AboutPage" (
    "id" SERIAL NOT NULL,
    "hero_badge" TEXT,
    "hero_title" TEXT,
    "hero_paragraph1" TEXT,
    "hero_paragraph2" TEXT,
    "hero_image_url" TEXT,
    "value_1_icon" TEXT,
    "value_1_title" TEXT,
    "value_1_desc" TEXT,
    "value_2_icon" TEXT,
    "value_2_title" TEXT,
    "value_2_desc" TEXT,
    "value_3_icon" TEXT,
    "value_3_title" TEXT,
    "value_3_desc" TEXT,
    "value_4_icon" TEXT,
    "value_4_title" TEXT,
    "value_4_desc" TEXT,
    "milestone_1_year" TEXT,
    "milestone_1_title" TEXT,
    "milestone_1_desc" TEXT,
    "milestone_2_year" TEXT,
    "milestone_2_title" TEXT,
    "milestone_2_desc" TEXT,
    "milestone_3_year" TEXT,
    "milestone_3_title" TEXT,
    "milestone_3_desc" TEXT,
    "milestone_4_year" TEXT,
    "milestone_4_title" TEXT,
    "milestone_4_desc" TEXT,
    "milestone_5_year" TEXT,
    "milestone_5_title" TEXT,
    "milestone_5_desc" TEXT,
    "team_1_name" TEXT,
    "team_1_role" TEXT,
    "team_1_image" TEXT,
    "team_2_name" TEXT,
    "team_2_role" TEXT,
    "team_2_image" TEXT,
    "team_3_name" TEXT,
    "team_3_role" TEXT,
    "team_3_image" TEXT,
    "stat_years" TEXT,
    "stat_flavors" TEXT,
    "stat_countries" TEXT,
    "stat_customers" TEXT,

    CONSTRAINT "AboutPage_pkey" PRIMARY KEY ("id")
);
