-- AlterTable
ALTER TABLE "SiteSettings" ADD COLUMN     "cta_badge_text" TEXT DEFAULT 'Perfect for Gifting',
ADD COLUMN     "cta_highlight" TEXT DEFAULT 'Golden Perfection?',
ADD COLUMN     "cta_primary_link" TEXT DEFAULT '/products',
ADD COLUMN     "cta_primary_text" TEXT DEFAULT 'Shop Now',
ADD COLUMN     "cta_secondary_link" TEXT DEFAULT '/contact',
ADD COLUMN     "cta_secondary_text" TEXT DEFAULT 'Corporate Orders',
ADD COLUMN     "cta_subtitle" TEXT DEFAULT 'Order our premium biscuits today and discover why customers trust us.',
ADD COLUMN     "cta_title" TEXT DEFAULT 'Ready to Experience',
ALTER COLUMN "about_subtitle" SET DEFAULT 'The story behind our craft',
ALTER COLUMN "about_title" SET DEFAULT 'A Legacy of Delicious Moments',
ALTER COLUMN "hero_badge" SET DEFAULT 'Premium Artisan Quality Since 1980',
ALTER COLUMN "hero_cta_primary_label" SET DEFAULT 'View Products',
ALTER COLUMN "hero_cta_primary_link" SET DEFAULT '/products',
ALTER COLUMN "hero_cta_secondary_label" SET DEFAULT 'Our Story',
ALTER COLUMN "hero_cta_secondary_link" SET DEFAULT '/about',
ALTER COLUMN "highlight1_text" SET DEFAULT 'Over 40 years of baking excellence',
ALTER COLUMN "highlight1_title" SET DEFAULT 'Since 1980',
ALTER COLUMN "highlight2_text" SET DEFAULT 'Every biscuit crafted by hand',
ALTER COLUMN "highlight2_title" SET DEFAULT 'Made with Love',
ALTER COLUMN "highlight3_text" SET DEFAULT 'Only the finest, organic materials',
ALTER COLUMN "highlight3_title" SET DEFAULT 'Natural Ingredients',
ALTER COLUMN "highlight4_text" SET DEFAULT 'Recognized for quality worldwide',
ALTER COLUMN "highlight4_title" SET DEFAULT 'Award Winning',
ALTER COLUMN "stat1_label" SET DEFAULT 'Years of Excellence',
ALTER COLUMN "stat1_value" SET DEFAULT '40+',
ALTER COLUMN "stat2_label" SET DEFAULT 'Happy Customers',
ALTER COLUMN "stat2_value" SET DEFAULT '50K+',
ALTER COLUMN "stat3_label" SET DEFAULT 'Unique Flavors',
ALTER COLUMN "stat3_value" SET DEFAULT '25+';
