-- AlterTable
ALTER TABLE "SiteSettings" ADD COLUMN     "about_subtitle" TEXT,
ADD COLUMN     "about_title" TEXT,
ADD COLUMN     "hero_badge" TEXT,
ADD COLUMN     "hero_cta_primary_label" TEXT,
ADD COLUMN     "hero_cta_primary_link" TEXT,
ADD COLUMN     "hero_cta_secondary_label" TEXT,
ADD COLUMN     "hero_cta_secondary_link" TEXT,
ADD COLUMN     "highlight1_text" TEXT,
ADD COLUMN     "highlight1_title" TEXT,
ADD COLUMN     "highlight2_text" TEXT,
ADD COLUMN     "highlight2_title" TEXT,
ADD COLUMN     "highlight3_text" TEXT,
ADD COLUMN     "highlight3_title" TEXT,
ADD COLUMN     "highlight4_text" TEXT,
ADD COLUMN     "highlight4_title" TEXT,
ADD COLUMN     "stat1_label" TEXT,
ADD COLUMN     "stat1_value" TEXT,
ADD COLUMN     "stat2_label" TEXT,
ADD COLUMN     "stat2_value" TEXT,
ADD COLUMN     "stat3_label" TEXT,
ADD COLUMN     "stat3_value" TEXT;
